"""init

Revision ID: c092b72017dc
Revises: 
Create Date: 2024-06-27 09:38:49.651053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c092b72017dc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('nombre')
    )
    op.create_table('tipo_producto',
    sa.Column('id_tipo', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_tipo')
    )
    op.create_table('usuarios',
    sa.Column('cedula_identidad', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('apellido', sa.String(length=50), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=False),
    sa.Column('correo_electronico', sa.String(length=100), nullable=False),
    sa.Column('contrasena', sa.String(length=255), nullable=False),
    sa.Column('tipo_usuario', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['tipo_usuario'], ['roles.nombre'], ),
    sa.PrimaryKeyConstraint('cedula_identidad'),
    sa.UniqueConstraint('correo_electronico')
    )
    op.create_table('pedidos',
    sa.Column('id_pedido', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('fecha_pedido', sa.Date(), nullable=False),
    sa.Column('cantidad_productos', sa.Integer(), nullable=False),
    sa.Column('metodo_env', sa.String(length=50), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['id_cliente'], ['usuarios.cedula_identidad'], ),
    sa.PrimaryKeyConstraint('id_pedido')
    )
    op.create_table('productos',
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('id_artesano', sa.Integer(), nullable=False),
    sa.Column('id_tipo', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=False),
    sa.Column('cantidad_disponible', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('dimensiones', sa.String(length=50), nullable=False),
    sa.Column('peso', sa.Double(precision=10, asdecimal=2), nullable=False),
    sa.Column('imagen', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['id_artesano'], ['usuarios.cedula_identidad'], ),
    sa.ForeignKeyConstraint(['id_tipo'], ['tipo_producto.id_tipo'], ),
    sa.PrimaryKeyConstraint('id_producto')
    )
    op.create_table('calificaciones',
    sa.Column('id_calificacion', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('calificacion', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['usuarios.cedula_identidad'], ),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], ),
    sa.PrimaryKeyConstraint('id_calificacion')
    )
    op.create_table('detalles_pedido',
    sa.Column('id_detalle', sa.Integer(), nullable=False),
    sa.Column('id_pedido', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Double(precision=10, asdecimal=2), nullable=False),
    sa.ForeignKeyConstraint(['id_pedido'], ['pedidos.id_pedido'], ),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], ),
    sa.PrimaryKeyConstraint('id_detalle')
    )
    op.create_table('encargos',
    sa.Column('encargo_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('estado_encargo', sa.String(length=50), nullable=False),
    sa.Column('fecha_encargo', sa.Date(), nullable=False),
    sa.Column('metodo_envio', sa.String(length=50), nullable=False),
    sa.Column('descripcion_encargo', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['usuarios.cedula_identidad'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id_producto'], ),
    sa.PrimaryKeyConstraint('encargo_id')
    )
    op.create_table('pedido_producto',
    sa.Column('id_pedido_producto', sa.Integer(), nullable=False),
    sa.Column('id_pedido', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('cant_unidades', sa.Integer(), nullable=False),
    sa.Column('total', sa.Double(precision=10, asdecimal=2), nullable=False),
    sa.ForeignKeyConstraint(['id_pedido'], ['pedidos.id_pedido'], ),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], ),
    sa.PrimaryKeyConstraint('id_pedido_producto')
    )
    op.create_table('resenas',
    sa.Column('id_resena', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('fecha_invencion', sa.Date(), nullable=False),
    sa.Column('creador', sa.String(length=100), nullable=False),
    sa.Column('anios_produccion', sa.Integer(), nullable=False),
    sa.Column('anecdotas', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], ),
    sa.PrimaryKeyConstraint('id_resena')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resenas')
    op.drop_table('pedido_producto')
    op.drop_table('encargos')
    op.drop_table('detalles_pedido')
    op.drop_table('calificaciones')
    op.drop_table('productos')
    op.drop_table('pedidos')
    op.drop_table('usuarios')
    op.drop_table('tipo_producto')
    op.drop_table('roles')
    # ### end Alembic commands ###
